image: Visual Studio 2022

build_script:
  - dotnet restore src\HeadlessChromium.Puppeteer.Lambda.Dotnet.sln
  - dotnet build src\HeadlessChromium.Puppeteer.Lambda.Dotnet.sln --no-restore -c Release

test_script:
  - dotnet test src\HeadlessChromium.Puppeteer.Lambda.Dotnet.Tests\HeadlessChromium.Puppeteer.Lambda.Dotnet.Tests.csproj --no-build -c Release
